// POST /api/send-email — DEPRECATED (Phase ROA-1).
//
// Since ROA-1, the broker notification email is generated by
// /api/roa-submissions/notify-email, which loads the canonical PDF from
// Storage rather than accepting arbitrary browser-supplied bytes. This
// endpoint is retained only long enough to give any straggling clients a
// clear 410 with the new route.

import { requireAuthenticatedBroker } from './_lib/auth.js';

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });
  // Auth is still checked so this endpoint cannot be used as an unauthenticated
  // probe against the deprecation contract.
  const user = await requireAuthenticatedBroker(req, res);
  if (!user) return;
  return res.status(410).json({
    error: 'endpoint_deprecated',
    message: 'Use POST /api/roa-submissions/notify-email with { submissionId, to, subject, body }.',
  });
}
